// Builds src/components/icons.js: only the Lucide icons the app names, instead of the whole set (~1,700 icons).
// Any quoted PascalCase word in src/ that is a Lucide icon is kept. Run `npm run icons` after using a new icon.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import * as Lucide from 'lucide'

const names = new Set(['Circle']) // the fallback
const walk = (dir) => {
  for (const f of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, f.name)
    if (f.isDirectory()) walk(p)
    else if (/\.(jsx?|mjs)$/.test(f.name) && f.name !== 'icons.js') {
      for (const [, n] of readFileSync(p, 'utf8').matchAll(/['"`]([A-Z][A-Za-z0-9]+)['"`]/g)) if (Array.isArray(Lucide[n])) names.add(n)
    }
  }
}
walk('src')
const list = [...names].sort()
writeFileSync('src/components/icons.js', `// Generated by scripts/icons.mjs — do not edit. ${list.length} icons.\nexport { ${list.join(', ')} } from 'lucide'\n`)
console.log(`${list.length} icons`)
